[build]
target = "index.html"
dist = "dist" 
public_url = "/"

[serve]
addresses = ["127.0.0.1"]
port = 8080
open = true

# Enable file watching for hot reload
watch = ["src", "styles", "index.html", "assets"]

# Copy assets directory to dist
[[assets]]
src = "assets"
dest = "assets"
